config/routes.rb
CthulhuCasebook::Application.routes.draw do
  resource  :character, :only => [:edit, :new, :create], :controller => 'characters', :path_names => { :edit => 'profile' }
  resources :characters, :only => [:show] do
    resource :conferences, :only => [:show]
    resources :gifts, :only => [:new, :update]
  end
  resources :gifts, :only => [] do
    member do
      get 'accept'
      get 'reject'
    end    
  end
  resources :equipment, :only => [] do
    resources :trappings, :only => [:update, :destroy]
  end
  
  resource  :location,  :only => [:show], :controller => 'locations' do
    resources :passage, :only => [:show], :controller => 'passages'
  end
  resources :messages, :only => [:index, :show]
  resources :locations, :only => [:index] do
    resource  :monster, :only => [:new], :controller => 'monsters', :path_names => { :new => 'strategy' }
    resources :monster, :only => [:show], :controller => 'monsters'    
  end
  resource  :monster, :only => [:new], :controller => 'monsters', :path_names => { :new => 'strategy' }
  resources :monster, :only => [:show], :controller => 'monsters'
  
  resources :encounters, :only => [:show] do
    resources :paths, :only => [:show]
  end
  resources :demises, :only => [:show]
  resources :friends, :only => [:index]
  resources :importunity, :only => [:create], :controller => 'importunities' do
    member do
      get 'accept'
      get 'reject'
    end
  end

  resources :help, :only => [:show], :controller => 'help'
  resource :application,  :only => [:show]
  resource :facebook, :only => [], :controller => 'facebook' do
    member do
      get :channel
    end
  end
  root :to => 'application#show'
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  before_filter :require_template, :only => [:show]
  
  def show
    render :template => @template
  end
  
  private
  
  def require_template
    @template = "help/#{params[:id]}"
    redirect_to root_path and return unless template_exists?(params[:id], "help")
  end
end

app/views/help/basics.html.erb
<section>
  <div class="page-header">
    <h2>The Basics of Gameplay</h2>
  </div>

  <div>
	<p>Cthulhu Casebook is a text-based horror RPG where you investigate (or consummate) Lovecraftian plots and period intrigue in the roaring '20s.</p>
	
    <p>As an outsider called back to your hometown by mysterious compulsions, you can freely explore Arkham's historic locations where countless encounters await. You must rely on a limited supply of clues to pursue these encounters in a manner of your choosing, but in doing so you'll discover just who you really are while unlocking deeper plots in ever stranger places.</p>
  </div>
</section>

app/views/help/character.html.erb
<section>
  <div class="page-header">
    <h2>Character</h2>
  </div>

  <div>
    <p>When you first begin, <%= link_to 'your character', edit_character_path %> has a name and gender, but is otherwise a mere silhouette of a long-lost stranger whose heart's desire and driving obsession with the Mythos remains unknown. By choosing paths through <%= link_to 'encounters', location_path %> you'll come to define just who you are by whatever apropos characteristics you decide to nurture and indulge.</p>

    <h3>Skills</h3>
    <br />
    <p>Your greatest defining characteristics are your skills. These eight skills are used whenever you face an encounter's challenge, meaning that your capabilities will grow based around how you choose to conduct your investigations and the types of investigations you seek out.</p>
    <p>Whenever you use a skill, you will gain experience in that skill. When your experience in that skill reaches the same value as the skill itself, your expertise in that skill will advance and your experience meter for that skill will be reset.</p>

    <h3>Belongings</h3>
    <br />
    <p>In the course of your investigations you'll acquire all manner of practical and exotic items, from currency to candles. These are requisite to various encounters and paths, and you must often seek out certain items to further a plot. Sometimes you can use your belongings in perpetuity, and sometimes they must be spent or lost.</p>

    <h3>Gear</h3>
    <br />
    <p>Certain items - such as weapons and apparel - can be equipped in order to grant modifiers to your skills and other characteristics. You can freely equip yourself as you please at any time from your <%= link_to 'profile', edit_character_path %>, but you only have two hands at a time with which to brandish weaponry.</p>
    <p></p>

    <h3>Knowledge</h3>
    <br />
    <p>Knowledge is power and currency, and will often be required during encounters. Your knowledge will take many forms, from the slanderous to the revelational, and will generally be awarded from various encounters around Arkham. Once spent following a path, your knowledge is no longer useful, and your knowledge of the given area is reduced accordingly.</p>
  </div>
</div>

app/views/help/demise.html.erb
<section>
  <div class="page-header">
    <h2>Your Demise</h2>
  </div>

  <div>
	<p>While you will never truly die, you are nevertheless subject to a catalogue of unpleasant demises which hinder life. These usually take the form of highly abnormal pathology incurred while confronting monsters and magic. When a certain pathology - usually wounds or insanity - becomes too serious, you will meet your respective demise.</p>
	
    <p>Upon your demise you'll be transported to another place to revive. For example: with grave wounds, you will awaken in St. Mary's Hospital; or with crippling insanity you'll find yourself held up in Arkham Sanitarium. Other pathologies will bring you to even more unusual locations.</p>

    <p>In these locations you will have the opportunity to experience unique encounters, many of which contribute to relieving your pathology. Depending on the severity of your demise, you will be remanded to your fate for some amount of time during which you must explore your surroundings until you can make your return to Arkham.</p>

    <h3>Revival</h3>
    <br />
    <p>Casual investigation and disbursement of clues will be enough to eventually revive you from your demise, but you can usually take more drastic paths to accelerate your recovery at some painful price. One way or the other, encounters in such a location will usually let you advance toward freedom heedfully or with abandon.</p>

    <p>Once you've been able to reduce your crippling pathology to normal, you will be offered an encounter that returns you to Arkham.</p> 
    <p>Needless to say, it's best to <%= link_to 'monitor your pathology', edit_character_path %> and ensure you're not in danger of a demise and, if so, to then find encounters around Arkham that treat your pathology <em>before</em> it's too late.</p>
  </div>
</section>

app/views/help/encounters.html.erb
<section>
  <div class="page-header">
    <h2>Encounters</h2>
  </div>

  <div>
    <p>Your main casebook activity will be having <%= link_to 'encounters', location_path %> at locations around the <%= link_to 'Arkham map', locations_path %>. Most encounters will have several paths you can follow that represent different approaches to the problem at hand and which confer various rewards. You can usually repeat an encounter many times, and many encounters will only become available at a location after you've met certain conditions.</p>
	
    <h3>Paths</h3>
    <br />
    <p>Most encounters will offer several paths which you can follow depending on whim and the nature of your soul. Each path confers appropriate awards, and indeed you will often repeatedly follow a path until you can meet the requirements of another plot-related task, for example raising your underworld skill before visiting the local mob.</p>
    <p>Like encounters themselves, some paths are only available when you meet certain conditions, such as developing a skill to a high level, possessing enough money, or affiliation with a special faction.</p>

    <h3>Challenges</h3>
    <br />
    <p>While some paths can be followed automatically, others require you to pass a challenge, usually against one of your skills. Success will be determined by the level of your skill and the difficulty of the challenge. Failing a challenge has no consequences, but you will only receive the path's awards after you succeed.</p>

    <h3>Awards</h3>
    <br />
    <p>Once you succeed in a challenge or else simply follow an unchallenged path, you'll receive the respective awards. These can vary widely from training your skills to granting knowledge or new belongings. Awards will also frequently reduce and penalize your <%= link_to 'profile', edit_character_path %>, as much of the progress in your investigations will cary a price.</p>
  </div>
</section>

app/views/help/map.html.erb
<section>
  <div class="page-header">
    <h2>City Map</h2>
  </div>

  <div>
    <p>Every neighborhood location in Arkham contains different encounters and plots, and you will travel from location to location using the <%= link_to 'city map', locations_path %>. Although you are free to travel as much as you like, the more you do so the more likely you are to be attacked by monsters.</p>
    <p>In due course, plots will often require you to travel around to find the next thread leading to their conclusion, and you may often find a dangling thread in a surprising location.</p>

    <h3>Neighborhoods</h3>
    <br />
    <p>The main locations in Arkham are:</p>
    <ul>
      <li>Northside</li>
      <li>Downtown</li>
      <li>Rivertown</li>
      <li>Merchant District</li>	
      <li>Easttown</li>
      <li>French Hill</li>
      <li>Southside</li>
      <li>Miskatonic University (restricted)</li>
      <li>Outskirts (restricted)</li>
    </ul>
	
    <h3>Passages</h3>
    <br />
    <p>You can only reach adjacent locations from your current location, and traveling across Arkham - say from Northside to Uptown - will require several moves.</p>
    <p>Some passages will only become open to you under certain conditions, such as visiting the Miskatonic University campus.</p>
  </div>
</section>

app/views/help/monsters.html.erb
<section>
  <div class="page-header">
    <h2>Monsters</h2>
  </div>

  <div>
    <p>The shadows of Arkham are stalked by wandering monsters who will appear and attack as you travel around the <%= link_to 'map', locations_path %>. The frequency of attacks depends on the nature of the monster, and if you have attracted their attention. Once attacked, however, you must deal with the monster before doing anything else.</p>

    <p>Because wandering monsters can only attack you when you travel on the <%= link_to 'map', locations_path %>, the more often you move around the more likely you are to come under attack.</p>

    <h3>Strategy</h3>
    <br />
    <p>To face the monster you must choose one of several strategies, from fighting to hiding to sorcery. All monsters are more susceptible to some strategies than others, and your skill in the strategies will also vary. Chose a corresponding strategy in which you happen to be skilled and you'll have a good chance to survive the attack unharmed.</p>
    <p>More powerful monsters will be harder to defeat, and you may need to battle them many times to overcome their attack and resume your investigations. If you're desperate or can afford it, however, you may also <em>automatically</em> defeat a monster by using clues equal to its power.</p>

    <h3>Victory and Defeat</h3>
    <br />
    <p>When you defeat a monster you'll arrive safely at your destination, and often gain some additional reward from the ordeal.</p>
    <p>When a monster defeats you, however, you will remain where you are, and suffer a variety of penalties such as wounds, madness, or a witch's curse. These penalties will affect your pathology and ultimately lead to your demise.</p>
  </div>
</section>

app/views/help/plots.html.erb
<section>
  <div class="page-header">
    <h2>Plots</h2>
  </div>

  <div>
    <p>Plots are mysteries which unfold over the course of many different <%= link_to 'encounters', location_path %>, often across many locations around the <%= link_to 'map', locations_path %>. You can discover new plot threads by visiting locations and having an encounter there, unlocking the first stage of a plot; as you continue to find and solve new stages of the plot, more plot-based encounters become available on the <%= link_to 'map', locations_path %>.</p>
	
	<p>Once you've started investigating a plot, you can track your progress at <%= link_to 'your lodgings', messages_path %>.</p>
	
	<h3>Types</h3>
    <br />
    <p>Plots come in many forms, from simple mysteries which reveal secrets about the Mythos, to mundane intrigues around Arkham, to the study of powerful grimoires. However, every plot will always contain a series of encounters, has a definite conclusion, and can usually only be undertaken once.</p>

	<h3>Requirements</h3>
    <br />
    <p>The first encounter which begins a plot will always have a number of requirements you must satisfy before it becomes available. These requirements cover a range of facts about your character, and are usually difficult and obscure to come by; for example, obtaining membership in an organization or having spoken to someone regarding a sinister turn of events.</p>

	<h3>Awards</h3>
    <br />
    <p>The final encounter which ends a plot will generally confer a few notable awards that, for better or worse, will change you forever, and may also reveal even deeper plot threads for you to pursue.</p>
  </div>
</section>