config/routes.rb
CthulhuCasebook::Application.routes.draw do
  resource  :character, :only => [:edit, :new, :create], :controller => 'characters', :path_names => { :edit => 'profile' }
  resources :characters, :only => [:show] do
    resource :conferences, :only => [:show]
    resources :gifts, :only => [:new, :update]
  end
  resources :gifts, :only => [] do
    member do
      get 'accept'
      get 'reject'
    end    
  end
  resources :equipment, :only => [] do
    resources :trappings, :only => [:update, :destroy]
  end
  
  resource  :location,  :only => [:show], :controller => 'locations' do
    resources :passage, :only => [:show], :controller => 'passages'
  end
  resources :messages, :only => [:index, :show]
  resources :locations, :only => [:index] do
    resource  :monster, :only => [:new], :controller => 'monsters', :path_names => { :new => 'strategy' }
    resources :monster, :only => [:show], :controller => 'monsters'    
  end
  resource  :monster, :only => [:new], :controller => 'monsters', :path_names => { :new => 'strategy' }
  resources :monster, :only => [:show], :controller => 'monsters'
  
  resources :encounters, :only => [:show] do
    resources :paths, :only => [:show]
  end
  resources :demises, :only => [:show]
  resources :friends, :only => [:index]
  resources :importunity, :only => [:create], :controller => 'importunities' do
    member do
      get 'accept'
      get 'reject'
    end
  end

  resources :help, :only => [:show], :controller => 'help'
  resource :application,  :only => [:show]
  resource :facebook, :only => [], :controller => 'facebook' do
    member do
      get :channel
    end
  end
  root :to => 'application#show'
end

app/models/message.rb
class Message
  include MongoMapper::Document
  
  key :sender, String, :required => true
  key :title, String, :required => true
  key :text, String, :required => true
  key :created_at, Date
  
  belongs_to :character
  
  after_create :update_character_messages_count
  
  def self.find_readable(character, message_id=nil)
    q = where '$or' => [{:character_id => character._id}, {:character_id => nil}, {:character_id => {'$exists' => false}}]
    q = q.first(:_id => message_id) if message_id
    q
  end  
  
  private 
  
  def update_character_messages_count
    character.update_attribute(:messages_count, character.messages_count + 1) if character
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :require_no_demise, :only => [:index]
  
  def index
    @encounters = Encounter.find_location( 'lodgings' )
    @messages = Message.find_readable(current_character)
    current_character.reset_messages_count
  end
  
  def show
    @message = Message.find_readable(current_character, params[:id])
  end
end

app/views/messages/index.html.erb
<section class='row'>
  <div>	
    <h1>    
      <span class='pull-left'><%= image_tag 'placeholder300x300.png', :width => 96, :height => 64 %>&nbsp;</span>
      <span><%= current_character.lodgings.name %></span>
    </h1>
	<p><%= simple_format current_character.lodgings.description %></p>
  </div>
</section>

<section class='row'>

  <div class='well span8'>	
    <h3>A Davenport of Mysterious Cases</h3>
    <br />
    <table class='table table-bordered'>
      <% if current_character.profile.find_tagging('plots').tags.size > 0 %>
        <thead style='background:#fff'><th>You've staked ground in unsure footing, but appear to be making progress with the following plots...</th></thead>
      <% end %>
      <% current_character.profile.find_tagging('plots').tags.each do |plot| %>
        <tr>
          <td>
            <h4><%= plot._id.titleize %></h4>
			<span class="progress progress-success">
			  <div class="bar" style="width: <%= [((plot.value.to_f / 15.0) * 100).to_i, 1].max %>%;"></div>
			</span>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
	
  <div class='well well-condensed span3'>	
    <ul class="nav nav-list">
      <li class="nav-header">Messages from people as well as Other Things</li>
      <% @messages.each do |message| %>
        <li>
          <strong><%= link_to message.title, message_path(message) %></strong><br />
          <small>From: <%= message.sender %></small>
        </li>
      <% end %>
    </ul>
  </div>

</section>


<div style='display:none'>
<h1>
  <%= image_tag 'placeholder75x75.png', :class => 'picture-frame tilt', :align => 'left' %> 
  <small>Your Lodgings:</small><br> <%= current_character.lodgings.name %>
</h1>
<p><%= simple_format current_character.lodgings.description %></p>

<ul class='horizontal'>
  <li class='half'>
    <ul class='plain'>
      <li>
        <h3>A Davenport of Mysterious Cases</h3>
        <p>You've staked ground in unsure footing, but appear to be making progress with the following plots...</p>
      </li>
      <% current_character.profile.find_tagging('plots').tags.each do |plot| %>
        <li>
          <label class='half'><%= plot._id.titleize %> </label>
          <progress max="15" value="<%= plot.value %>"></progress>
        </li>
      <% end %>

      <% if current_character.profile.find_tagging('research').tags.size > 0 %><li><h3>Studies</h3></li>
        <% current_character.profile.find_tagging('research').tags.each do |tome| %>
          <li>
            <label class='half'><%= tome._id.titleize %> </label>
            <progress max="50" value="<%= tome.value %>"></progress>
          </li>
        <% end %>
      <% end %>
    </ul>
  </li>
  <li class='half'>		
    <ul class='plain'>
      <li>
        <h3>Messages from people as well as Other Things</h3>
      </li>
      <% @messages.each do |message| %>
        <li>
          <strong><%= link_to message.title, message_path(message) %></strong><br />
          <small>From: <%= message.sender %></small>
        </li>
      <% end %>
    </ul>
  </li>
</ul>

<% unless lodgings_encounters.blank? %>
  <hr />
  <div>
    <hgroup>
      <h3>Personal Encounters</h3>
      <h5>Intimate obsessions and privy studies best pursued at leisure in the privacy of your lodgings</h5>
    </hgroup>
    <ul class='horizontal polaroids'>
      <% lodgings_encounters.each do |encounter| %>
        <li>
          <%= link_to encounter_path(encounter), :rel => 'nofollow' do %>
            <%= image_tag 'placeholder96x96.png' %>
            <%= simple_format word_wrap(encounter.title, :line_width => 15) %>
          <% end %>
        </li>
      <% end %>
    </ul>	
  </div>
<% end %>
</div>

app/views/messages/show.html.erb
<section>
  <div>
    <h1>
      <%= @message.title %><br/> <small>from <%= @message.sender %></small>
    </h1>
    <br />
  </div>

  <p class='well'><%= raw @message.text %></p>

  <%= link_to messages_path, :class => 'btn btn-default input-medium' do %>
    Back to Lodgings
  <% end %>
<section>