config/routes.rb
CthulhuCasebook::Application.routes.draw do
  resource  :character, :only => [:edit, :new, :create], :controller => 'characters', :path_names => { :edit => 'profile' }
  resources :characters, :only => [:show] do
    resource :conferences, :only => [:show]
    resources :gifts, :only => [:new, :update]
  end
  resources :gifts, :only => [] do
    member do
      get 'accept'
      get 'reject'
    end    
  end
  resources :equipment, :only => [] do
    resources :trappings, :only => [:update, :destroy]
  end
  
  resource  :location,  :only => [:show], :controller => 'locations' do
    resources :passage, :only => [:show], :controller => 'passages'
  end
  resources :messages, :only => [:index, :show]
  resources :locations, :only => [:index] do
    resource  :monster, :only => [:new], :controller => 'monsters', :path_names => { :new => 'strategy' }
    resources :monster, :only => [:show], :controller => 'monsters'    
  end
  resource  :monster, :only => [:new], :controller => 'monsters', :path_names => { :new => 'strategy' }
  resources :monster, :only => [:show], :controller => 'monsters'
  
  resources :encounters, :only => [:show] do
    resources :paths, :only => [:show]
  end
  resources :demises, :only => [:show]
  resources :friends, :only => [:index]
  resources :importunity, :only => [:create], :controller => 'importunities' do
    member do
      get 'accept'
      get 'reject'
    end
  end

  resources :help, :only => [:show], :controller => 'help'
  resource :application,  :only => [:show]
  resource :facebook, :only => [], :controller => 'facebook' do
    member do
      get :channel
    end
  end
  root :to => 'application#show'
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @friends = current_user.facebook_friends
    @characters = current_character.friends
    @importunity = Importunity.first(:user_id => current_character.user_id)
  end
end

app/views/friends/index.html.erb
<h1>Your Friends.</h1>
<p>They can help with your investigations in various ways.</p>

<% if @characters.blank? %>
  <p>You are alone - Are friends a liability, getting in the way or plotting treachery? Or are they too simple-minded for the task at hand? Perhaps you're just protecting those you hold dear from the influence of cosmic horror.</p>

  <p>Whatever the reason, you can always <u>invite a friend to join</u> if your burden grows too heavy for one individual to carry alone.</p>
<% else %>
  <p>Some persons of talent and expertise are known to you:</p>
  <ul class='horizontal polaroids'>
    <% @characters.each do |character| %>
      <li>
        <%= link_to "/characters/#{character._id}", :rel => 'nofollow' do %>
          <%= image_tag 'placeholder96x96.png' %>
          <big><%= character.formal_name %></big>
        <% end %>
      </li>
    <% end %>
  </ul>	
<% end %>
<hr />

<% if @importunity && !@importunity.pending_user_ids.blank? %>
  <h3>The Importunities of Strangers!</h3>
  <p>Suspicious... or propitious? It seems your reputation proceeds you as strangers importune upon your sense of camaraderie!</p>

  <ul class='horizontal'>
    <% @importunity.pending_user_ids.each do |uid| %>
      <li>
        <% if character = Character.first(:user_id => uid) %>
          <%= image_tag 'placeholder64x64.png', :class => 'picture-frame' %>
          <big><%= link_to character.formal_name, "/characters/#{character._id}" %></big><br />

           <%= link_to 'accept their friendship', accept_importunity_path(uid), :class => 'button' %><br />
           <%= link_to 'reject their friendship', reject_importunity_path(uid), :class => 'button' %>

        <% end %>
      </li>
    <% end %>
  </ul>
  <hr />
<% end %>

<h3>Importune a Stranger</h3>
<p>If you know the <strong>case #</strong> of a stranger of some talent and expertise, you can importune their friendship by entering it here:</p>

<%= form_tag importunity_index_path do |f| %>
  <p><%= text_field_tag :user_id, nil, :placeholder => 'case number' %></p>
  <p><%= submit_tag 'Importune' %></p>
<% end %>