config/routes.rb
CthulhuCasebook::Application.routes.draw do
  resource  :character, :only => [:edit, :new, :create], :controller => 'characters', :path_names => { :edit => 'profile' }
  resources :characters, :only => [:show] do
    resource :conferences, :only => [:show]
    resources :gifts, :only => [:new, :update]
  end
  resources :gifts, :only => [] do
    member do
      get 'accept'
      get 'reject'
    end    
  end
  resources :equipment, :only => [] do
    resources :trappings, :only => [:update, :destroy]
  end
  
  resource  :location,  :only => [:show], :controller => 'locations' do
    resources :passage, :only => [:show], :controller => 'passages'
  end
  resources :messages, :only => [:index, :show]
  resources :locations, :only => [:index] do
    resource  :monster, :only => [:new], :controller => 'monsters', :path_names => { :new => 'strategy' }
    resources :monster, :only => [:show], :controller => 'monsters'    
  end
  resource  :monster, :only => [:new], :controller => 'monsters', :path_names => { :new => 'strategy' }
  resources :monster, :only => [:show], :controller => 'monsters'
  
  resources :encounters, :only => [:show] do
    resources :paths, :only => [:show]
  end
  resources :demises, :only => [:show]
  resources :friends, :only => [:index]
  resources :importunity, :only => [:create], :controller => 'importunities' do
    member do
      get 'accept'
      get 'reject'
    end
  end

  resources :help, :only => [:show], :controller => 'help'
  resource :application,  :only => [:show]
  resource :facebook, :only => [], :controller => 'facebook' do
    member do
      get :channel
    end
  end
  root :to => 'application#show'
end

app/models/character.rb
class Character
  include MongoMapper::Document
  
  MAX_CLUES = 50
  
  key :name, String, :required => true
  key :clues, Integer, :required => true, :default => MAX_CLUES
  key :gender, String
  key :biography, String  
  key :messages_count, Integer, :default => 1
  key :character_friend_ids, Array  
  key :last_seen_at, Time
    
  belongs_to :user
  belongs_to :monster
  has_one    :profile
  has_many   :messages
  
  after_create :populate_profile
  
  def self.find_for_users(user_ids)
    where(:user_id => {'$in' => user_ids} )
  end
  
  def self.new_for_user(params)
    params ||= {}
    params[:user_id] ||= User.create(:email => "#{rand(1000000)}@example.com")._id
    params[:last_seen_at] = Time.now.utc
    Character.new params
  end
  
  def self.reclue
    Character.set({:clues => {'$lt' => MAX_CLUES}}, :clues => MAX_CLUES)
  end
  
  def formal_name
    gender == 'female' ? "Ms. #{name}" : "Mr. #{name}"
  end
  
  def friends
    character_friend_ids.blank? ? [] : Character.where(:_id => {'$in' => character_friend_ids })
  end  
  
  def local_friends
    if character_friend_ids.blank?
      []
    else
      friends = Profile.where('character_id' => {'$in' => character_friend_ids} )
      friends = friends.where('taggings._id' => 'location', 'taggings.tags' => {:_id => 'current', :value => location.value})
      friends = friends.map{ |p| p.character }
      friends = friends.select{ |c| c.last_seen_at && c.last_seen_at >= (Time.now.utc - 6.hours) }
      friends
    end
  end
  
  def spend_clues(amount=1)
    self.clues = self.clues - amount
    self.last_seen_at = Time.now.utc
  end
  
  def encounter_monster!(monster_id)
    self.monster_id = monster_id
    save
  end
  
  def fighting_monster?
    !monster_id.blank?
  end
  
  def location
    profile.get('location', 'current') if profile
  end
  
  def lodgings
    Lodging.find(profile.get('lodgings', 'current').value) if profile
  end  
  
  def relocate!(current_location)
    if profile    
      profile.set('location', 'current', current_location) 
      profile.save
    end
  end
  
  def reset_messages_count
    return if messages_count == 0
    
    self.messages_count = 0
    self.save
  end
  
  def befriend!(character)
    cid = character._id.to_s
    unless character_friend_ids.include?(cid)
      self.character_friend_ids << cid 
      save
    end
  end
  
  def skill_progress(skill)
    val = profile.get('experience', skill).count
    return 0 if val == 0
    
    val = val.to_f / (profile.get('skills', skill).count.to_f + 1)
    (val * 100).round(0)
  end
  
  def last_seen
    self.last_seen_at = Time.now.utc if last_seen_at.blank? || last_seen_at < Time.now.utc - 10.minutes
  end
  
  private 
  
  def populate_profile
    self.profile = Profile.create(:character => self)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def edit
    @character = current_character
    @equipment = Equipment.find_for @character.profile.find_tagging('equipment')
  end
  
  def show
    if @character = Character.find(params[:id])
      @equipment = Equipment.find_for @character.profile.find_tagging('equipment')
    end
  end
  
  def new
    @character = Character.new
  end
  
  def create
    @character = Character.new_for_user params[:character]
    if @character.save
      session[:user_id] = @character.user_id
      authenticate_character @character._id
      redirect_to intro_encounter_path
    else
      render 'new'
    end
  end  
  
  private
  
  def intro_encounter_path
    encounter_path(:homecoming)
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
  def trapping_label(area)
    if @character.profile.trappings.send(area)
      "<span class='label'> #{@character.profile.trappings.send(area)['title'].gsub(/Right/,'R.').gsub(/Left/,'L.')}</span>"
    else
      '<em>Nothing special</em>'
    end
  end
end

app/views/characters/edit.html.erb
<section class='row'>
  <div class="span7">	
    <h1>    
      <span class='pull-left'><%= image_tag 'placeholder300x300.png', :width => 64, :height => 64 %>&nbsp;</span>
      <span><%= @character.formal_name %></span>
    </h1>
    <p>
      Case # <strong><%= @character.user_id %></strong> (share with friends)
      <br/>
      Currently at: <strong><%= @character.location.value.titleize %></strong>
    </p>

	<div class="btn-group">
	  <button class="btn">Trappings</button>
	  <button class="btn dropdown-toggle" data-toggle="dropdown">
	    <span class="caret"></span>
	  </button>
	  <ul id="trappings-tabs" class="dropdown-menu dropdown-menu-table">
        <li>
          <strong>Headwear:</strong> 
          <%= raw trapping_label('head') %>
        </li>
        <li>
          <strong>Overwear:</strong> 
          <%= raw trapping_label('body') %>
        </li>
        <li>
          <strong>Handwear:</strong> 
          <%= raw trapping_label('hands') %>
        </li>
        <li>
          <strong>R. Hand:</strong>
          <%= raw trapping_label('right_hand') %>
        </li>
        <li>
          <strong>L. Hand:</strong> 
          <%= raw trapping_label('left_hand') %>
        </li>
        <li>
          <strong>Footwear:</strong> 
          <%= raw trapping_label('feet') %>
        </li>
	  </ul>
	</div>
	
  </div>	

  <div class="span5">
    <br />
    <div class='well well-condensed'>
      <h3>Pathology</h3>
      <dl class="dl-horizontal">
        <% @character.profile.find_tagging('pathology').tags.each do |tag| %>
          <dt><%= tag._id.titleize  %></dt> 
          <dd>
			<div class="progress progress-labeled progress-<%= tag.count < 10 ? 'warning' : 'danger' %>">
			  <div class="bar" style="width: <%= [((tag.value.to_f / 20.0) * 100).to_i, 1].max %>%;"></div>
              <big><%= tag.value %></big>
			</div>
          </dd>
        <% end %>
      </dl>	
    </div>	
  </div>		
</section>

<section>
  <div class="tabbable">
    <ul class="nav nav-tabs" data-tabs="tabs">
      <li class="active"><a href="#skills-panel" data-toggle="tab">Skills</a></li>
      <li><a href="#belongings-panel" data-toggle="tab">Items</a></li>
      <li><a href="#equipment-panel" data-toggle="tab">Gear</a></li>
      <li><a href="#knowledge-panel" data-toggle="tab">Knowledge</a></li>
    </ul>
  </div>	

  <div class="tab-content">
    <div class="tab-pane active" id='skills-panel'>
      <div class='well well-condensed'>
        <dl class="dl-horizontal">
          <% @character.profile.find_tagging('skills').tags.each do |tag| %>
            <dt><%= tag._id.titleize  %>: <big>0<%= tag.value %></big></dt> 
            <dd>
		      <div class="progress progress-labeled progress-success">
		  	    <div class="bar" style="width: <%= @character.skill_progress(tag._id) %>%;"></div>
              </div>
            </dd>
          <% end %>
        </dl>
      </div>	
    </div>	

    <div class="tab-pane" id='belongings-panel'>
      <div class='well well-condensed'>
        <ul class="thumbnails">
          <% @character.profile.find_tagging('belongings').tags.each do |tag| %>
            <li>
              <div class="thumbnail">                
                <h5><%= simple_format word_wrap("#{tag.value} #{tag._id.titleize}", :line_width => 15) %></h5>
                <%= image_tag 'placeholder64x64.png', :class => 'picture-frame' %>
              </div>
            </li>	
          <% end %>
        </ul>
      </div>	
    </div>

    <div class="tab-pane fade" id='equipment-panel'>
      <div class='well well-condensed'>
        <ul class="thumbnails">
          <% @character.profile.find_tagging('equipment').tags.each do |tag| %>
            <li>
              <div class="thumbnail">                
                <h5><%= simple_format word_wrap("#{tag.value} #{tag._id.titleize}", :line_width => 15) %>	</h5>
                <%= image_tag 'placeholder64x64.png', :class => 'picture-frame' %>

	            <% if equipment = @equipment.select{|e| e._id == tag._id}.first %>
	              <p><%= equipment.modifier_display %></p>
	              <% if @character.profile.trappings.location_of(equipment._id).blank? %>
	                <%= link_to 'Equip This', equipment_trapping_path(equipment._id, equipment.location), :method => :put, :class => 'btn btn-info btn-small' %>
                  <% else %>
                    <%= link_to 'Equipped', 'javascript:void(0)', :class => 'btn btn  btn-small disabled' %>
	              <% end %>
	            <% end %>
              </div>
            </li>	
          <% end %>
        </ul>
      </div>	
    </div>

    <div class="tab-pane fade" id='knowledge'>
      <div class='well well-condensed'>	
        <ul class="thumbnails">
          <% @character.profile.find_tagging('knowledge').tags.each do |tag| %>
            <li>
              <div class="thumbnail">                
                <h5><%= simple_format word_wrap("#{tag.value} #{tag._id.titleize}", :line_width => 15) %>	</h5>
                <%= image_tag 'placeholder64x64.png', :class => 'picture-frame', :width => 32, :height => 32 %>
              </div>
            </li>	
          <% end %>
        </ul>
      </div>	
    </div>	
  </div>
</section>

app/views/characters/new.html.erb
<header class="jumbotron subhead">
  <h1>Dreadful Adventure Awaits...</h1><br />
  <p>Cthulhu Casebook is a <strong>text-based horror RPG</strong> where you investigate (or consummate) Lovecraftian plots and period intrigue in the roaring '20s. You'll pursue the Great Old Ones and their minions through storied mystery and obtain deadly Mythos lore empowering you in mankind's secret battle against cosmic extinction.<span style='display:inline'><a href='#new-character' class='visible-phone'><i class='icon-chevron-down'></i></a></span></p>
</header>

<section id='new-character'>
  <br />
  <div class="hero-unit flat">
    <h1>Create a Character</h1>

    <p>Cthulhu Casebook is <strong>completely free to play</strong> using the <strong>Book of Faces</strong>.</p>

    <%= form_for @character, :url => character_path, :class => "form-inline" do |f| %>
      Mr. <%= f.radio_button :gender, :male %> &nbsp; &nbsp;
      Mrs. <%= f.radio_button :gender, :female %> &nbsp; &nbsp;

      <%= f.text_field :name, :placeholder => 'Enter a name', :class => 'medium-input' %> <br>
      <%= f.submit 'Start Investigating', :class => 'btn btn-success btn-large btn-wide' %>
    <% end %>
  </div>
</section>

<p>In a world of occult horror, victorian attire, and pulp adventure, Cthulhu Casebook remains faithful to the literature of <strong>H. P. Lovecraft</strong> and less faithful to history as your investigations take you through sleepy Arkham, Miskatonic Valley, and beyond.</p>

<p>Be forewarned, however, that the game is in an archean stage, and exists under the rule of violent, ceaseless,  erratic development, and that your progress may at times be lost as updates are deployed. <span style='display:inline'><a href='#new-character' class='visible-phone'><i class='icon-chevron-up'></i></a></span></p>

app/views/characters/show.html.erb
<h1>
  <%= image_tag 'placeholder75x75.png', :class => 'picture-frame tilt', :align => 'left' %> 
  <%= @character.formal_name %>
</h1>
<p>
<% if @character.character_friend_ids && @character.character_friend_ids.include?(current_character._id.to_s) %>	
  You are friends with this person. Are they worthy? Would you like to <%= link_to "give them one of your belongings to assist their investigations", new_character_gift_path(@character) %>?
<% elsif %>  
  This person has <% @character.character_friend_ids.size %> friends.
<% end %>
</p>
<br />

<ul class='horizontal'>
  <li class='half'>	
    <ul class='plain'>
      <li><h4>Skills</h4></li>
      <% @character.profile.find_tagging('skills').tags.each do |tag| %>
        <li>
          <label class='third'><%= tag._id.titleize %></label> <strong><%= tag.count > 9 ? tag.count : "0#{tag.count}" %></strong>
          &nbsp;&nbsp;
          <progress max="100" value="<%= @character.skill_progress(tag._id) %>"></progress>
        </li>
      <% end %>
    </ul>
  </li>
  <li class='half'>
    <h4>Pathology</h4>
    <ul class='plain'>
      <% @character.profile.find_tagging('pathology').tags.each do |tag| %>
        <li><%= tag._id.titleize  %> <strong><%= tag.value %></strong> <progress max="20" value="<%= tag.value %>"></progress></li>
      <% end %>
    </ul>
  </li>
</ul>